import Head from "next/head";
import { Navbrar } from "@/components/navbar";
import { FooterAlt } from "@/components/footer-alt";
import { AboutUs } from "@/components/about-us";

export default function AboutUsPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbrar />
      <AboutUs />
      <FooterAlt />
    </>
  );
}
