import Head from "next/head";
import { Hero } from "@/components/hero";
import { WorkProcess } from "@/components/work-process";
import { Navbrar } from "@/components/navbar";
import { Services } from "@/components/services";
import { About } from "@/components/about";
import { Pricing } from "@/components/pricing";
import { PriceProcess } from "@/components/price-process";
import { Testimonials } from "@/components/testimonials";
import { Footer } from "@/components/footer";
import { BlogArea } from "@/components/blog-area";
import { CounterArea } from "@/components/counter-area";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbrar />
      <Hero />
      <Services />
      <About />
      <Pricing />
      <PriceProcess />
      <Testimonials />
      <WorkProcess />
      <CounterArea />
      <BlogArea />
      <Footer />
    </>
  );
}
