import Head from "next/head";
import { WorkProcess } from "@/components/work-process";
import { Navbrar } from "@/components/navbar";
import { Services } from "@/components/services";
import { About } from "@/components/about";
import { Pricing } from "@/components/pricing";
import { PriceProcess } from "@/components/price-process";
import { BlogArea } from "@/components/blog-area";
import { CounterArea } from "@/components/counter-area";
import { OurProjects } from "@/components/our-projects";
import { OurClients } from "@/components/our-clients";
import { FooterAlt } from "@/components/footer-alt";
import { Testimonials2 } from "@/components/testimonial2";
import { Hero2 } from "@/components/hero-2";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbrar />
      <Hero2 />
      <Services />
      <About />
      <Pricing />
      <PriceProcess />
      <Testimonials2 />
      <WorkProcess />
      <CounterArea />
      <BlogArea />
      <OurProjects />
      <OurClients />
      <FooterAlt />
    </>
  );
}
